#!/usr/bin/env bash

set -eo pipefail

if [[ -x "$(command -v kr)" ]]; then
  kr unpair > /dev/null
  echo "✅ Krypton detected and unpaired"
fi

UNLOAD_AT="${1:-"17:40"}"
DIR="$(dirname "$0")"
KEY="$DIR/id_rsa"
if [[ ! -f "$KEY" ]]; then
  echo "👻 No private key is present at $KEY. Please add a key. Exiting while leaving the volume mounted..."
  exit 1
fi

NOW_TIMESTAMP="$(date +%s)"
UNLOAD_AT_TIMESTAMP="$(date -jf '%H:%M:%S' "$UNLOAD_AT:00" +%s)"
UNLOAD_IN="$((UNLOAD_AT_TIMESTAMP-NOW_TIMESTAMP))"

if [[ $UNLOAD_IN -lt 0 ]]; then
  UNLOAD_IN="$((10*60))"
  UNLOAD_AT_TIMESTAMP="$(expr "$(date +"%s")" + $UNLOAD_IN)"
  echo "😱 It is past $UNLOAD_AT - should you be working? Loading the key for 10 minutes."

  UNLOAD_AT="$(date -r $UNLOAD_AT_TIMESTAMP +"%H:%M")"
  echo "🤫 (If you know what you're doing add the time to unload the key, e.g: $0 $UNLOAD_AT)"
fi

set +e
/usr/bin/ssh-add -L >> /dev/null 2>&1
HAS_IDENTITIES=$?
set -e

if [[ "$HAS_IDENTITIES" == 0 ]]; then
  /usr/bin/ssh-add -D >> /dev/null 2>&1
  echo "🧹 Existing loaded ssh keys have been removed from this machine's agent"
fi

/usr/bin/ssh-add -t "$UNLOAD_IN" "$KEY" >> /dev/null 2>&1
echo "🔑 Your ssh key has been added to this machine's agent"
echo "🕔 The key will be automatically unloaded at $UNLOAD_AT"

echo "⏏️  The volume will be ejected now..."
/usr/sbin/diskutil umount force "$DIR" >> /dev/null 2>&1
